spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/valoria
spring.datasource.username=${DB_USERNAME:valoria}
spring.datasource.password=${DB_PASSWORD:valoria123}
spring.jpa.hibernate.ddl-auto=update